### PR TITLE
Fix Travis by updating zc.buildout version

### LINKED ISSUE #7: Tests are currently broken
See https://travis-ci.org/github/zopefoundation/cipher.encryptingstorage

### PR DESCRIPTION
**Pull request by jugmac00**
This fixes #7 

modified:   buildout.cfg
modified:   requirements.txt

### CODE REVIEW

**Comment by mgedmin** [comment]
Build failures are due to
> Download error on https://pypi.org/simple/zope.minmax/: [Errno 104] Connection reset by peer -- Some packages may not be found!

on Python 3.5, and

> Getting distribution for 'venusian>=1.0'.
> error: Setup script exited with error: 'egg_base' must be a directory name (got `src`)

on 2.7.

I've restarted the 3.5 build.

I've never heard of `egg_base` before, so I left the 2.7 build alone.

**Comment by jugmac00** [comment]
Ok, I shall not touch any packages without tox :-(

I ran the test locally with 3.6 - and that worked, and as the original error was a `need this, but got that` version mismatch, I deduced fixing one version will fix all -> wrooong

And now here we are... keeping Python 2.7 support is not biggo... at least that's what I used to say - until ... now :-D

**Comment by mgedmin** [comment]
@jamadden volunteered to do that ;)

Although I wonder if maybe we should deprecate and archive cipher.encryptingstorage.  I don't trust its crypto implementation.

**Comment by jamadden** [comment]
The problem appears to be in the venusian 3.0.0 sdist. I'm not sure, exactly, what, though, because it uses the weird declarative syntax in setup.cfg instead of setup.py for *everything*, including package finding:
```ini
[options]
package_dir =
    =src
packages = find:
python_requires = >=3.5

[options.packages.find]
where = src
```

Is that an extra `=`? (EDIT: Or maybe our older version of setuptools doesn't support all that external data?)

But anyway, it doesn't matter: venusian 3.0 is Python 3 only, so the next step would be to pin it backwards for Python 2; zc.buildout can do that fairly easily, IIRC. (Or wait for the updated zc.buildout release that respects `python_requires`.) I've never used this package or looked at its buildout, but I'm sorta surprised to see a ZODB storage pulling in venusian for its tests in the first place...

But like @mgedmin, I thought this package was at least semi-deprecated since the cryptography hasn't been reviewed.

**Comment by mgedmin** [comment]
> Is that an extra =?

I bet it's the same as `package_dir={'': "src"}`, only in .ini syntax.

**Review by mgedmin — APPROVED** [review]
LGTM

**Review by jamadden — APPROVED** [review]

**Pull request merged**
