### PR TITLE
Config with pure python

### PR DESCRIPTION
**Pull request by icemac**
The tests are currently broken – I fixed some by adding `use_extension_bytes = True` but the other ones break on different code.

Does anyone have an idea how to fix this?

### CODE REVIEW

**Comment by icemac** [comment]
Strange, locally (on MacOS) I get the following failures: (But only on Python 2.7!)

```python
Failure in test checkFlushNeededAfterTruncate (cipher.encryptingstorage.tests.test_zodb.FileStorageZlibTests)
Traceback (most recent call last):
  File ".../lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File ".../cipher.encryptingstorage/.tox/py27/lib/python2.7/site-packages/ZODB/tests/testFileStorage.py", line 327, in checkFlushNeededAfterTruncate
    self.checkFlushAfterTruncate(True)
  File ".../cipher.encryptingstorage/.tox/py27/lib/python2.7/site-packages/ZODB/tests/testFileStorage.py", line 314, in checkFlushAfterTruncate
    b'foo' if fail else b'bar')
  File ".../lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File ".../lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 'bar' != 'foo'


Failure in test checkFlushNeededAfterTruncate (cipher.encryptingstorage.tests.test_zodb.FileStorageZlibTestsWithBlobsEnabled)
Traceback (most recent call last):
  File ".../lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File ".../cipher.encryptingstorage/.tox/py27/lib/python2.7/site-packages/ZODB/tests/testFileStorage.py", line 327, in checkFlushNeededAfterTruncate
    self.checkFlushAfterTruncate(True)
  File ".../cipher.encryptingstorage/.tox/py27/lib/python2.7/site-packages/ZODB/tests/testFileStorage.py", line 314, in checkFlushAfterTruncate
    b'foo' if fail else b'bar')
  File ".../lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File ".../lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 'bar' != 'foo'
```

**Comment by vincentfretin** [comment]
I'm not using this package anymore, the project where I was using it is dead now. Sorry, I won't be able to review or help with this.

**Comment by icemac** [comment]
@vincentfretin Thank you for informing. I removed you from the reviewers list.

**Review by jugmac00 — APPROVED** [review]
lgtm

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
